print('Olá, mundo')
print(2 + 3)
print('2 + 3')
print('2' + '3')
print('Olá, ' + 'Mundo')
print('Olá,', 'Mundo')
print('O resultado da soma de 2 + 3 é:', 2 + 3)
print(10 * (5 + 7) / 4)
print(10 * (5 + 7 / 4))
